apiVersion: v1 # Required. v1 is only valid value.
kind: cypress # Required.
sauce:
  region: us-west-1 # Required. 
  concurrency: 40 # Optional. Controls how many suites are executed at the same time.
cypress:
  version: 13.10.0 # Required. See https://docs.saucelabs.com/web-apps/automated-testing/cypress/#supported-testing-platforms for a list of supported versions. Can also be value "package.json" and will pick up the value from there.
  configFile: "cypress.config.js" # Required. Input path to your cypress config file.

# The following section controls what files are available in the context of a test run (unless explicitly excluded by .sauceignore).
rootDir: ./
suites: # Required.
  - name: "Chrome on Windows" # Required. 
    browser: "chrome" # Required. 
    platformName: "Windows 11" # Optional
    screenResolution: "1920x1080" # Optional 
    shard: spec # Optional. Allocate one VM per spec for a high degree of parallelism.
    config: # Required
      specPattern: ["cypress/e2e/**/*.*"] # Required. Cypress native glob support.
